### ISSUE TITLE
GuzzleRetryAfterHandler

### ISSUE THREAD

**Issue by glebstar** [caseyamcl/guzzle_retry_middleware#1]
[Symfony\Component\Debug\Exception\FatalThrowableError]          
  Call to undefined function App\Models\GuzzleRetryAfterHandler()

**Comment by caseyamcl** [comment]
HI @glebstar .. It looks like I made a typo in the documentation!  Thanks for catching that.

I have corrected it.  Instead of..

```
$stack->push(GuzzleRetryAfterHandler());
```

...try...

```
$stack->push(GuzzleRetryMiddleware());
```

Also, it looks like you might need to import the class namespace.
