### ISSUE TITLE
Warning: usleep(): Number of microseconds must be greater than or equal to 0

### ISSUE THREAD

**Issue by JeroenVanLeusden** [caseyamcl/guzzle_retry_middleware#12]
## Detailed description
Occasionally see this error in the logs. Don't know how to reproduce yet.

```PHP
Warning: usleep(): Number of microseconds must be greater than or equal to 0 in /data/web/magento2/vendor/caseyamcl/guzzle_retry_middleware/src/GuzzleRetryMiddleware.php on line 282
```

## Possible implementation
Set minimum delay to be zero?

**Comment by caseyamcl** [comment]
This is an interesting bug.  I can ensure a non-negative number, but it would be good to know what is generating a negative timeout.  Can you provide more details about the context?  Is it possible to provide the URL your using the library to access, or other contextual info?

**Comment by JeroenVanLeusden** [comment]
Not yet, It's a very rare warning. I'll keep an eye on the logs and hopefully can give you some more information when it happens again.
