### ISSUE TITLE
 [Enhancement] Customize name of `RetryAfter` header

### ISSUE THREAD

**Issue by jamesaspence** [caseyamcl/guzzle_retry_middleware#20]
## Detailed description

I'm consuming an API that sets a custom header, `X-Rate-Limit-Reset`, to indicate how long I should wait before attempting another request. I'd like to be able to use that header instead of `Retry-After`.

## Context

As detailed above, this will help us consume this API a bit easier.

## Possible implementation

Be able to specify a `retry_after_header` option in the options array that allows us to specify the name of this header. Default to `Retry-After`.

I will likely create a fork and PR to attempt this in the near future.

**Comment by jamesaspence** [comment]
Created a PR here: https://github.com/caseyamcl/guzzle_retry_middleware/pull/21

After reading the documentation more closely, `default_retry_multiplier` can be used to determine an exact timeout, so I can achieve this result without this option. However, I figure the PR might be useful for others in the future.

**Comment by caseyamcl** [comment]
I like it the idea!  I'll evaluate this PR as soon as possible.

**Comment by caseyamcl** [comment]
Merged into v2.4
