### ISSUE TITLE
Set new header option in retry callback

### ISSUE THREAD

**Issue by whobutsb** [caseyamcl/guzzle_retry_middleware#22]
Is there a way to set a new header option with each retry callback?  For example if I receive a 429 rate limiting error and wanted to use a different JWT access token.  Can I modify the request object to send a different request? 

Example: 

```
        $listener = function($attemptNumber, $delay, &$request, &$options, $response) {
            $request->setHeader('x-token', $this->access_tokens[$attemptNumber]);
        };
```

Thank you for the assistance.

**Comment by caseyamcl** [comment]
There certainly is!  However, the `Request` object is [immutable](https://www.php-fig.org/psr/psr-7/#3-interfaces), so you have to overwrite the reference inside of your callback function.  The following syntax should do what you need:

```
        $listener = function($attemptNumber, $delay, &$request, &$options, $response) {
            $request = $request->withHeader('x-token', $this->access_tokens[$attemptNumber]);
        };
```

To see example code of this in action, refer to [the `testRetryCallbackReferenceModification` in the test file](https://github.com/caseyamcl/guzzle_retry_middleware/blob/master/tests/GuzzleRetryMiddlewareTest.php#L676).

**Comment by whobutsb** [comment]
Thank you for the helpful reply!  It is much appreciated!
