### ISSUE TITLE
[Enhancement] Customize date format of `RetryAfter` header

### ISSUE THREAD

**Issue by boddie2** [caseyamcl/guzzle_retry_middleware#24]
## Detailed description

I came across this date format 2020-11-10T18:44:00.000+00:00 in the`RetryAfter` header.

## Context

It would be useful to have a possibility to specify the date format of this header.

## Possible implementation

Add an option in the options array that allows us to specify the date format of this header. Default constant DATE_FORMAT

**Comment by caseyamcl** [comment]
Hi @boddie2, I implemented this enhancement in v2.6; refer to the [README file](https://github.com/caseyamcl/guzzle_retry_middleware#setting-a-custom-date-format-for-the-retry-after-header) for documentation.
