### ISSUE TITLE
[Enhancement] Option to stop retrying after x seconds

### ISSUE THREAD

**Issue by SpartakusMd** [caseyamcl/guzzle_retry_middleware#28]
Is there a way to specify a parameter of a max execution time for request?

## Detailed description

Example I want to allow at most 30 seconds per request. This means that if we are in the middle of a retry it should stop. The problem is that each request/retry can take an indefinite amount of time, so we cannot hardcode a specific number of retries with a specific interval.

## Possible implementation

Track start time of the request, and calculate a timeout per retry 🤔

**Comment by SpartakusMd** [comment]
Here's the idea. We allow for 5 retries with `retry_on_timeout` enabled. We can receive timeout response up to 2 minutes. What I would like is a way to allow no more than 5 minutes to get the response with all the retries. Example:
- Fetching /products endpoint with 5 retries allowed
- Received timeout after 2m
- Received timeout after 30s
- Received timeout after 2m
- Here I would like to have the max allowed time to get the response calculated to 30 seconds (5m - 2m - 30s - 2m = 30s)

Currently I didn't see an option / a way to achieve this logic.

**Comment by caseyamcl** [comment]
I just added a new option that I _think_ covers this use-case: `give_up_after_secs`:

```php
# This will fail when either the number of seconds is reached, or the number of retry attempts is reached, whichever
# comes first 
$response = $client->get('/some-path', [
   'max_retry_attempts' => 10 
   'give_up_after_secs' => 10
]);```

See more details in the [README for version 2.7](https://github.com/caseyamcl/guzzle_retry_middleware/blob/v2.7/README.md#setting-a-hard-ceiling-for-all-retries)
