### ISSUE TITLE
[SUGGESTION] Callback for deciding retry timeout

### ISSUE THREAD

**Issue by mfn** [caseyamcl/guzzle_retry_middleware#3]
The current implementation implements a hard-coded algorithm with a `default_retry_multiplier`.

This may be to inflexible if someone may want to use other means, like 2<sup>retryCount - 1</sup> or similar.

As such it would be great if this could be a callback too, similar to what the `\GuzzleHttp\RetryMiddleware::__construct(delay)` does.

**Comment by caseyamcl** [comment]
Yep, I plan on implementing this.

I didn't include it thus far, because my focus was on the `Retry-After` use-case.  If you want to submit a PR and tests, feel free; otherwise I'll get it implemented as soon as I can.

**Comment by caseyamcl** [comment]
Hi @mfn ... As of today's release ([version 2.1](https://github.com/caseyamcl/guzzle_retry_middleware/releases/tag/2.1)), `default_retry_multiplier` now accepts a callable, per your suggestion.

You can read about how to use it here: <https://github.com/caseyamcl/guzzle_retry_middleware#setting-default-retry-delay>

Best regards!
