### ISSUE TITLE
Add a new option

### ISSUE THREAD

**Issue by wengooooo** [caseyamcl/guzzle_retry_middleware#32]
Add a new option, when the status code returns 200, can call the callback method, because some sites even if the status code returns 200, but the content is wrong, this time you should be able to set whether to retry

**Comment by caseyamcl** [comment]
@wengooooo , allow me to paraphrase to see if I understand your issue correctly:

You would like to add the ability to retry requests that have returned a successful `200` header, but have incorrect data.

I'm trying to think of a case in which the data would be incorrect at "X" point in time, but correct at future "Y" point in time. Can you provide an example?

**Comment by rus-ik** [comment]
+1 for the initial feature request..

Example:
  got response with HTTP OK (200), but the response body contains something like "{ ... "status": "error" ..}" or "<ResponseCode>Error</ResponseCode" or any other things indicating that despite of HTTP OK the request has to be resubmitted.

So having the requested callback we can parse the body and decide whether the request need a resubmittion

**Comment by caseyamcl** [comment]
Hi @rus-ik and @wengooooo, I've added a new `should_retry_callback` that handles this case; see the README.md: https://github.com/caseyamcl/guzzle_retry_middleware#custom-retry-decision-logic.

I originally was going to say this is out-of-scope for this library, but upon further reflection, I can see where it would be handy to have this functionality. The real world is messy...
